[2025-04-24T08:03:00.292+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-24T08:03:00.311+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_stock_project.dbt_snapshot manual__2025-04-24T07:41:56.593898+00:00 [queued]>
[2025-04-24T08:03:00.319+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_stock_project.dbt_snapshot manual__2025-04-24T07:41:56.593898+00:00 [queued]>
[2025-04-24T08:03:00.321+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-04-24T08:03:00.334+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): dbt_snapshot> on 2025-04-24 07:41:56.593898+00:00
[2025-04-24T08:03:00.344+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dbt_stock_project', 'dbt_snapshot', 'manual__2025-04-24T07:41:56.593898+00:00', '--job-id', '376', '--raw', '--subdir', 'DAGS_FOLDER/226_lab2_elt.py', '--cfg-path', '/tmp/tmplo_aggf5']
[2025-04-24T08:03:00.347+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=4176) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-24T08:03:00.347+0000] {standard_task_runner.py:105} INFO - Job 376: Subtask dbt_snapshot
[2025-04-24T08:03:00.348+0000] {standard_task_runner.py:72} INFO - Started process 4177 to run task
[2025-04-24T08:03:00.402+0000] {task_command.py:467} INFO - Running <TaskInstance: dbt_stock_project.dbt_snapshot manual__2025-04-24T07:41:56.593898+00:00 [running]> on host e8b5346887eb
[2025-04-24T08:03:00.492+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_stock_project' AIRFLOW_CTX_TASK_ID='dbt_snapshot' AIRFLOW_CTX_EXECUTION_DATE='2025-04-24T07:41:56.593898+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-24T07:41:56.593898+00:00'
[2025-04-24T08:03:00.494+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-24T08:03:00.507+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-24T08:03:00.510+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt snapshot --profiles-dir /home/***/.dbt --project-dir /opt/***/dbt']
[2025-04-24T08:03:00.519+0000] {subprocess.py:86} INFO - Output:
[2025-04-24T08:03:02.329+0000] {subprocess.py:93} INFO - [0m08:03:02  Running with dbt=1.8.7
[2025-04-24T08:03:03.257+0000] {subprocess.py:93} INFO - [0m08:03:03  Registered adapter: snowflake=1.8.1
[2025-04-24T08:03:04.131+0000] {subprocess.py:93} INFO - [0m08:03:04  Found 7 models, 10 data tests, 3 sources, 459 macros
[2025-04-24T08:03:04.136+0000] {subprocess.py:93} INFO - [0m08:03:04
[2025-04-24T08:03:04.138+0000] {subprocess.py:93} INFO - [0m08:03:04  Nothing to do. Try checking your model configs and model specification args
[2025-04-24T08:03:05.113+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-04-24T08:03:05.137+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-24T08:03:05.138+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dbt_stock_project, task_id=dbt_snapshot, run_id=manual__2025-04-24T07:41:56.593898+00:00, execution_date=20250424T074156, start_date=20250424T080300, end_date=20250424T080305
[2025-04-24T08:03:05.154+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-24T08:03:05.168+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-24T08:03:05.171+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
