[2025-04-22T15:53:56.992+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-22T15:53:57.016+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_stock_project.dbt_snapshot manual__2025-04-22T15:53:26.003425+00:00 [queued]>
[2025-04-22T15:53:57.029+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_stock_project.dbt_snapshot manual__2025-04-22T15:53:26.003425+00:00 [queued]>
[2025-04-22T15:53:57.032+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-04-22T15:53:57.050+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): dbt_snapshot> on 2025-04-22 15:53:26.003425+00:00
[2025-04-22T15:53:57.058+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dbt_stock_project', 'dbt_snapshot', 'manual__2025-04-22T15:53:26.003425+00:00', '--job-id', '288', '--raw', '--subdir', 'DAGS_FOLDER/226_lab2_elt.py', '--cfg-path', '/tmp/tmphrpyppji']
[2025-04-22T15:53:57.061+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1972) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-22T15:53:57.061+0000] {standard_task_runner.py:105} INFO - Job 288: Subtask dbt_snapshot
[2025-04-22T15:53:57.062+0000] {standard_task_runner.py:72} INFO - Started process 1973 to run task
[2025-04-22T15:53:57.128+0000] {task_command.py:467} INFO - Running <TaskInstance: dbt_stock_project.dbt_snapshot manual__2025-04-22T15:53:26.003425+00:00 [running]> on host 9d71c5fa265e
[2025-04-22T15:53:57.226+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_stock_project' AIRFLOW_CTX_TASK_ID='dbt_snapshot' AIRFLOW_CTX_EXECUTION_DATE='2025-04-22T15:53:26.003425+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-22T15:53:26.003425+00:00'
[2025-04-22T15:53:57.227+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-22T15:53:57.246+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-22T15:53:57.249+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt snapshot --profiles-dir /home/***/.dbt --project-dir /opt/***/dbt']
[2025-04-22T15:53:57.256+0000] {subprocess.py:86} INFO - Output:
[2025-04-22T15:53:59.229+0000] {subprocess.py:93} INFO - [0m15:53:59  Running with dbt=1.8.7
[2025-04-22T15:54:00.236+0000] {subprocess.py:93} INFO - [0m15:54:00  Registered adapter: snowflake=1.8.1
[2025-04-22T15:54:01.115+0000] {subprocess.py:93} INFO - [0m15:54:01  Found 7 models, 9 data tests, 3 sources, 459 macros
[2025-04-22T15:54:01.119+0000] {subprocess.py:93} INFO - [0m15:54:01
[2025-04-22T15:54:01.120+0000] {subprocess.py:93} INFO - [0m15:54:01  Nothing to do. Try checking your model configs and model specification args
[2025-04-22T15:54:02.110+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-04-22T15:54:02.138+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-22T15:54:02.139+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dbt_stock_project, task_id=dbt_snapshot, run_id=manual__2025-04-22T15:53:26.003425+00:00, execution_date=20250422T155326, start_date=20250422T155357, end_date=20250422T155402
[2025-04-22T15:54:02.193+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-22T15:54:02.209+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-22T15:54:02.212+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
